# Generated by Django 4.1.5 on 2023-02-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_last_sync_alter_user_login_otp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontact',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='usercontact',
            unique_together={('user', 'username')},
        ),
    ]
