# Generated by Django 4.1.5 on 2023-02-19 08:40

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_chatgroup_unique_id_alter_usercontact_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='unique_id',
            field=models.CharField(default=apps.accounts.models.get_default_random_string, max_length=10, unique=True),
        ),
    ]
