# Generated by Django 4.1.5 on 2023-02-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_bio_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='user/profile_photo/'),
        ),
    ]
